name: Node.js/Next.js CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install --prefix server
    - run: npm run dev --prefix server
    - run: npm install --prefix client
    - run: npm run build --prefix client
    # - run: npm test
      env:
        CI: true
